# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    mvc:
        favicon:
            enabled: false
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        url: jdbc:h2:file:./target/h2db/db/transactions;DB_CLOSE_DELAY=-1
        name:
        username: transactions
        password:
        h2:
            console:
                enabled: true

# ===================================================================
# Application specific properties
# ===================================================================

server:
  address: localhost
  port: 8080
